[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_22"]
buildCmd = "npx prisma generate && node node_modules/next/dist/bin/next build"

[deploy]
startCommand = "npx prisma db push --skip-generate && node node_modules/next/dist/bin/next start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
